# Independent workflow to allow greater flexibility in triggers and schedules
name: clang-format

on:
  push:
    paths-ignore:
      - 'doc/**'

env:
  CLANG_FORMAT_VERSION: 16

jobs:
  clang-format:
    name: Run clang-format
    runs-on: ubuntu-latest

    steps:
      # Checks-out Lethe with branch of triggering commit
      - name: Checkout code
        uses: actions/checkout@v2

      # Executes the specified version of clang-format
      - name: clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: 'applications source include'
          clangFormatVersion: ${{ env.CLANG_FORMAT_VERSION }}